#!/bin/bash

echo ""
echo "=========================================="
echo "   CLICKEAT ELASTICSEARCH - UTILIDADES"  
echo "=========================================="
echo ""
echo "🚀 SCRIPTS MULTIPLATAFORMA DISPONIBLES:"
echo ""
echo "📊 Verificación:"
echo "   npm run check:indices       - Estado de índices"
echo "   npm run sync:detect         - Detectar cambios"
echo "   npm run verify              - Verificar sistema completo"
echo ""
echo "🔄 Sincronización:"
echo "   npm run sync:incremental    - Sync completa"
echo "   npm run sync:clientes       - Solo clientes"
echo "   npm run sync:facturas       - Solo facturas" 
echo "   npm run sync:productos      - Solo productos"
echo "   npm run sync:rebuild        - Índices agregados"
echo ""
echo "⚙️ Configuración:"
echo "   npm run setup:complete      - Setup completo"
echo "   npm run utils               - Menú interactivo"
echo ""
echo "🧮 Demos y Pruebas:"
echo "   npm run demo:days           - Demo cálculo días"
echo "   npm run query:reactivation  - Consultas reactivación"
echo ""
echo "🗑️ Limpieza:"
echo "   npm run migrate:clean       - Limpiar índices"
echo ""
echo "==============================================="
echo "💡 TIP: Usa 'npm run utils' para menú interactivo"
echo "==============================================="
echo ""